# Nav2 minimal params for ROS 2 Humble

amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan
    min_particles: 200
    max_particles: 2000
    laser_model_type: likelihood_field
    update_min_a: 0.2
    update_min_d: 0.25
    transform_tolerance: 0.5

map_server:
  ros__parameters:
    use_sim_time: false

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      allow_unknown: true
      tolerance: 0.5
      motion_model_for_search: "MOORE"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false

      # --- ロボット運動学（最重要・最低限）---
      min_vel_x: -0.1
      max_vel_x:  0.4
      min_vel_y: -0.1
      max_vel_y:  0.4
      max_vel_theta: 0.8
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      min_speed_theta: 0.0

      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_lim_theta: 1.5
      decel_lim_x: -0.5
      decel_lim_theta: -1.5

      # シミュレーション設定（無難な初期値）
      sim_time: 2.0
      vx_samples: 20
      vtheta_samples: 20
      linear_granularity: 0.05
      angular_granularity: 0.025

      # ゴール条件・進捗
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.25
        stateful: true
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

behavior_server:
  ros__parameters:
    use_sim_time: false
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["backup", "spin", "wait"]
    backup:
      plugin: "nav2_behaviors/BackUp"
    spin:
      plugin: "nav2_behaviors/Spin"
    wait:
      plugin: "nav2_behaviors/Wait"

# ---- Global Costmap（静的地図 + センサ + インフレ）----
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      transform_tolerance: 0.5
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05

      # footprint か robot_radius のいずれか（最低限は半径でOK）
      robot_radius: 0.3

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_max_range: 3.5
          raytrace_max_range: 4.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 3.0

# ---- Local Costmap（ロボット周辺のローリング窓）----
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.5
      update_frequency: 15.0
      publish_frequency: 5.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05

      robot_radius: 0.3

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_max_range: 3.5
          raytrace_max_range: 4.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 3.0

# ---- Lifecycle 管理（最低限の2つ）----
lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ["map_server", "amcl"]

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - "controller_server"
      - "planner_server"
      - "bt_navigator"
      - "behavior_server"
      - "global_costmap"
      - "local_costmap"
